### ISSUE TITLE
Question about pretrained model

### ISSUE THREAD

**Issue by ziqi-zhang** [fangchangma/sparse-to-dense.pytorch#11]
Hi, thanks for sharing the code. These days I'm trying your code but I found that Lg10=nan(nan) and I didn't make it to train the net. I guess it was I didn't use any pretrained model. I wonder is the pretrained model on ImageNet necessary when using this version?

**Comment by fangchangma** [comment]
Hi Ziqi. Lg10=nan is expected since there are negative prediction values, and not using the imagenet-pretrained models is also fine (I just pushed another commit, and please use "--pretrained False" if you don't want to use the pretrained network). What exactly do you mean by "didn't make it to train the net"?
