### ISSUE TITLE
[NYU] Different Scaling in Training and Validation

### ISSUE THREAD

**Issue by maaft** [fangchangma/sparse-to-dense.pytorch#26]
When training on NYU both depth and rgb images are scaled for computational efficiency before applying rotation.

During training the images are scaled to:
```python
transforms.Resize(250.0 / iheight)
```
and during validation:
```python
transforms.Resize(240.0 / iheight)
```

I think that both scale-factors must be the same. Different scales implicitly change the distance of objects and therefore make it hard for the network to derive possibly learned "depth from scale".

**Comment by fangchangma** [comment]
Hi @maaft . That's good observation. In fact, the different scaling was intentional. Note that random rotation follows the rescaling operation during training. Consequently, if we rescaled to the target image size before the rotation, then the image would have missing pixels at the boundary. 

Hopefully the training dataset includes sufficient variation of depth scenes, and this small constant factor wouldn't cause too much of a trouble.

**Comment by maaft** [comment]
Yes, the fact that we need resizing because of rotation is without any doubt.

In another project I am currently working on, this actually made a huge difference for validation results.

I will run a test on a clean checkout for both variants (i.e. same/different scales) and report the metrics back to you.

**Comment by whubaichuan** [comment]
@maaft Hi, the download speed (13kb/s ) is too low when I use the command "wget http://datasets.lids.mit.edu/sparse-to-dense/data/nyudepthv2.tar.gz" even in VPN mode. How can I raise the download speed?

**Comment by maaft** [comment]
@whubaichuan maybe @fangchangma (author) can upload the dataset to a mirror.
