### ISSUE TITLE
Exploding REL value

### ISSUE THREAD

**Issue by timethy** [fangchangma/sparse-to-dense.pytorch#7]
During testing I noticed that the REL value is sometimes really large (e.g. 149966823318618112) which seems like we are dividing through almost zero.

After some debugging I found that this is indeed true,
in [metrics.py:42
](https://github.com/fangchangma/sparse-to-dense.pytorch/blob/master/metrics.py#L42):
`
self.absrel = (abs_diff / target).mean()
`
the minimal value of target is sometimes in the magnitude of e-10.

I believe this comes from resizing with interpolation of the depthmaps, resulting in sometimes really small but non-zero values.

I suggest that we can do
`
valid_mask >= EPS
`
for some EPS around 10e-9 or something like that.

Or of course, "fix" the interpolation in the data transform phase somehow.

**Comment by timethy** [comment]
While this is minor, it sometimes results in a
RuntimeError: Overflow when unpacking long

while writing into the csv which aborts training.

**Comment by fangchangma** [comment]
I understand the problem. However, I would suggest first making sure your data generation process is correct. Specifically, unlike a typical color image (which is dense), resizing sparse depth images can lead to spurious pixel values due to the bi-linear interpolation. 1e-10 is unlikely to be the real ground truth. 

If possible, try to avoid resizing sparse depth image. If resizing is indeed necessary, use nearest neighbor for interpolation, rather than bi-linear or cubic interpolation.

**Comment by timethy** [comment]
Hi, yes, excactly. I observed that this also happens with the NYUDepthv2 dataset, so maybe we should add a filter there to get rid of these small depth values.

**Comment by fangchangma** [comment]
The culprit of the exploding REL values is a bug in the rotation (I was using bilinear interpolation rather than nearest neighbor). This has been fixed and the REL value remains stable.
