### ISSUE TITLE
Question training data resolution!

### ISSUE THREAD

**Issue by duanyongli** [fangchangma/sparse-to-dense.pytorch#9]
The training data is resized and cropped to 228*304. On inference stage, i think the input image must be resized to the same size as training.
In my SLAM application, the resolution of input image is 480*640. In order to infer, input images must be downsampled to size of 228*304.
Can we train the model using resolution of 480*640? Thus avoid downsampling and upsampling.

**Comment by fangchangma** [comment]
To get a size of 480-by-640, you need the following changes in your fork:

1.  modify the [train transform](https://github.com/fangchangma/sparse-to-dense.pytorch/blob/f16e13f2e7d293ed3b5d713b6fcf268fad081f8c/nyu_dataloader.py#L51 ) and the [validation transform](https://github.com/fangchangma/sparse-to-dense.pytorch/blob/f16e13f2e7d293ed3b5d713b6fcf268fad081f8c/nyu_dataloader.py#L76) to load images of size 480-by-640
2. modify the output file size in the model definition https://github.com/fangchangma/sparse-to-dense.pytorch/blob/f16e13f2e7d293ed3b5d713b6fcf268fad081f8c/models.py#L9

Please let me know if these changes work.

**Comment by maaft** [comment]
What is exactly the reason for sampling down to 228x304? In your paper you cite [3] and [13] but they are also not really explaining the reason for that.

**Comment by fangchangma** [comment]
> What exactly is the reason for sampling down to 228x304? In your paper you cite [3] and [13] but they are also not really explaining the reason for that.

I downsampled to 228x304 simply for the sake of comparison against previous methods. I don't think there's anything magical to these numbers. Any size that is above 224x224 (minimal size for ResNet) should work fine.

**Comment by duanyongli** [comment]
@fangchangma After I modify the input and output size to 480*640, model works well.

**Comment by RCConnolly** [comment]
@fangchangma I am also trying to resize the model to train and output with a size of 480-640 (original image size of the NYU Depth data), but the implementation is now slightly different from your previous instructions since the code has changed.

I though the only necessary modification is to change the following line of code from (228, 304) to (480,640). 
https://github.com/fangchangma/sparse-to-dense.pytorch/blob/10efc6d60bddedd6f28f0532c108bb1d7ccdfc49/dataloaders/nyu_dataloader.py#L10

Unfortunately, this results in the following error:
`RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 81 and 60 in dimension 2 at /pytorch/aten/src/TH/generic/THTensorMoreMath.cpp:1307`

Any suggestions?

**Comment by whubaichuan** [comment]
@duanyongli @RCConnolly @timethy @AbigailFernandes Hi, the download speed (13kb/s ) is too low when I use the command "wget http://datasets.lids.mit.edu/sparse-to-dense/data/nyudepthv2.tar.gz" even in VPN mode. How can I raise the download speed? Looking forward to your reply.
